### PR TITLE
Migrate to sbt-typelevel

### PR DESCRIPTION
**Pull request by armanbilge**
This gets the ball rolling on main, but someone should backport this to series 2.x.

### CODE REVIEW

**Comment by armanbilge** [comment]
It takes 3 minutes to setup the microsite dependencies in CI ...

**Comment by rossabaker** [comment]
Yeah, it has to build a native sass compiler.  Might be able to cache the gem directory there?  🤷

**Comment by armanbilge** [comment]
Eh, I'd rather get lift-off on https://github.com/typelevel/sbt-typelevel/pull/68.

**Comment by rossabaker** [comment]
I can make jekyll operate like a static binary, but it requires making Nix part of the build pipeline rather than an opt-in dev shell.  If the sites aren't hard to convert, I'd also prefer to invest in Laika.

**Comment by armanbilge** [comment]
Yes, I think the sites should be easy to convert. I got https://github.com/typelevel/sbt-typelevel/pull/68 more ship-shape last night.

**Comment by armanbilge** [comment]
WDYT? https://armanbilge.github.io/vault

**Comment by rossabaker** [comment]
Looks good to me.  I don't know what that upload failure is about.

**Pull request merged**
