### PR TITLE
Add `Scalafmt`

### PR DESCRIPTION
**Pull request by danicheg**
Scalafmt rules are the same as in cats. Also added handy sbt commands for checking/formatting.

### CODE REVIEW

**Comment by rossabaker** [comment]
I'm in favor, but it's going to be a bad time if we continue to merge CE2 support forward.  How about:

1. Run this on the CE2 series branch instead.  You can probably cherry-pick the first two commits.
2. Merge to main.  Resolve conflicts by resetting to 804ff2a

That should keep a shared merge base between the two, and allow us to continue to roll forward fixes with minimal conflicts.

If you want to give that a try, cool.  If not, I'll give it a try with what you've started here.

**Comment by danicheg** [comment]
@rossabaker ah, I forgot about the branch with CE2. I would try to do what you suggest!

**Comment by rossabaker** [comment]
Okay, I _think_ everything interesting on series/2.x is already here.  If that's true, you should be able to merge that with the "ours" strategy (I know how to do it in magit; would need to look it up in git), and have that shared merge base _and_ not waste time manually keeping one side of all the conflicts.

**Comment by danicheg** [comment]
@rossabaker and it's done.

**Comment by rossabaker** [comment]
:tada: Nice work!

**Pull request merged**
